### ISSUE TITLE
Compatible with xy?

### ISSUE THREAD

**Issue by Artemis2017** [trikzon/Snow-Variants#4]
Hello,

it is planned that the Mod is compatible with:

Applied Energistics 2
Atum 2
Blockcraftery
Botania
Environmental Materials
Immersive Engineering
Quark
Tinkers Construct

It would be nice. Btw. Great Mod! Now my Buildings look more snowy in the cold Biomes :)

**Comment by Trikzon** [comment]
Yes, they are all on the to-do list
A lot more than I originally thought has to be done to get compatibility with other mods working correctly so it might take a while.

**Comment by Artemis2017** [comment]
Thank you!

**Comment by Artemis2017** [comment]
Thank you. Will be the compatible Updates comes for 1.12.2 and 1.13.2?

**Comment by Trikzon** [comment]
1.12.2 is the primary version so that will receive updates first. 1.13.2 is secondary

**Comment by Artemis2017** [comment]
Okay, thank you for the answer!
