### ISSUE TITLE
Spamming server log with notification whenever somebody right clicks anything

### ISSUE THREAD

**Issue by aprusik** [trikzon/Snow-Variants#8]
Hello!
Love the new update so that snow accumulates on rooves.  I'm running a custom modpack server for my friends and I.
Whenever anyone on the server right-clicks any block, despite what is in their hands, the server logs a message:

`[Server Thread/INFO] [STDOUT]: [trikzon.snowvariants.events.RightClickEvent:onBlockRightClicked:29]: <whatever the block is>`

Is this an intended feature, or perhaps some leftover debugging output?
I couldn't find a way to disable the messages in the config, but with even one person on the server it ends up dominating the server log.

**Comment by Trikzon** [comment]
Is this the latest 1.12.2 version?

**Comment by aprusik** [comment]
Yeah, sorry, forgot to mention that. Version 1.12.2-1.3.0.

**Comment by Trikzon** [comment]
alright, I see the problem. Will be fixed within the hour

**Comment by aprusik** [comment]
Awesome! Thanks.

**Comment by Trikzon** [comment]
Fixed. I accidentally left debug mode on, let me know if any other problems arise :)
https://www.curseforge.com/minecraft/mc-mods/snow-variants/files/2781333
